on:
  workflow_dispatch:
    inputs:
      gutenbergMobileVersion:
        required: true
      title:
        required: false
      prURL:
        required: false

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    env:
      GUTENBERG_MOBILE_VERSION: ${{ github.event.inputs.gutenbergMobileVersion }}
      PR_TITLE: ${{ github.event.inputs.title }}
      PR_URL: ${{ github.event.inputs.prURL }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update Gutenberg Mobile Version
        run: |
          sed -i "s/ext\.gutenbergMobileVersion = '.*'/ext.gutenbergMobileVersion = '$GUTENBERG_MOBILE_VERSION'/g" build.gradle
      - name: Compute vars
        id: vars
        run: |
          PR_TITLE_PREFIX = "Automated gutenberg-mobile version update"
          if [[ $PR_TITLE ]]; then
            PR_TITLE_PREFIX = $PR_TITLE
          fi
          
          # Check if the version contains a "-" character
          if [[ $GUTENBERG_MOBILE_VERSION == *"-"* ]]; then
            # Get the substring up to "-" which should be either "trunk" or the PR number
            VERSION_PREFIX=$(echo $GUTENBERG_MOBILE_VERSION | cut -d'-' -f1)

            if [[ "$VERSION_PREFIX" == "trunk" ]]; then
              echo ::set-output name=branch_name::update-gb-mobile-version/for-trunk-update
              echo ::set-output name=title::"$PR_TITLE_PREFIX for $VERSION_PREFIX"
            else
              echo ::set-output name=branch_name::update-gb-mobile-version/for-pr-$VERSION_PREFIX
              echo ::set-output name=title::"$PR_TITLE_PREFIX for PR $VERSION_PREFIX"
            fi
          else
            # If the version doesn't contain a "-", it should be a tag
            echo ::set-output name=branch_name::update-gb-mobile-version/for-tag-$GUTENBERG_MOBILE_VERSION
            echo ::set-output name=title::"$PR_TITLE_PREFIX for tag $GUTENBERG_MOBILE_VERSION"
          fi

          echo ::set-output name=commit_message::"Update gutenbergMobileVersion to $GUTENBERG_MOBILE_VERSION - $PR_URL"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: ${{ steps.vars.outputs.commit_message }}
          title: ${{ steps.vars.outputs.title }}
          branch: ${{ steps.vars.outputs.branch_name }}
          delete-branch: true
